numaproj-labs/numaplane

- api/v1/gitsync_types.go
- config/crd/bases/numaplane.numaproj.io.github.com.numaproj-labs_gitsyncs.yaml
- config/samples/numaplane.numaproj.io_v1_gitsync.yaml
Adding `TargetRevision` to specify the revision to sync to for a given repository path in GitSync.
> chore: add TargetRevision to GitSync 

- Dockerfile
This PR should speed up the docker build quite a lot, especially when we have large go dependencies. With a persistent cache for packages means that even if you rebuild a layer, you only download new or changed packages instead of downloading from fresh.
> Speed up the docker build with a go build cache

- api/v1/gitsync_types.go
- config/crd/bases/numaplane.numaproj.io.github.com.numaproj-labs_gitsyncs.yaml
- internal/git/gitsync_processor.go
- internal/git/gitsync_processor_test.go
This PR adds the logic to fetch all remote branches for correct `TargetRevision` resolution. It also allows root directory as repo `Path`.
> chore: Fetch all remote branches for resolution 

- Makefile
- config/manager/kustomization.yaml
Running `make deploy` edits the kustomization.yaml file for the Controller to change the image name from its default to a new name. The default recently changed from "controller" to "numaplane-controller", but the call to `kustomize edit` didn't get changed.
As part of this, I'm changing the default `config/manager/kustomization.yaml` as well. This is what the file looks like if you do `make deploy` (not setting IMG or IMAGE_FULL_PATH). Note this file will change locally if we run `make deploy IMAGE_FULL_PATH=x`, so we shouldn't check in that temporary change. I thought about adding this file to .gitignore, but wasn't sure since what if we want to change the file in the future?
> default image has a new name

- Makefile
When using the debugger, sometimes one cannot print the values of certain variables, which have been "optimized" out of the binary. By specifying GCFLAGS to "all=-N -l", this won't happen. I made this the default but you can also run `GCFLAGS="" make build` if you want an optimized binary. 
I tested:
`make build`
`make run`
`GCFLAGS="" make build`
`GCFLAGS="" make run`
> allow building non-optimized code for debugging purposes

- internal/git/gitsync_processor.go
Close https://github.com/numaproj-labs/numaplane/issues/62
We should not treat `git.NoErrAlreadyUpToDate` as error which simply means the remote repo has no change.
> Avoid throw error when git remote repo has no change

- Makefile
- config/manager/manager.yaml
Deployed controller specs
```bash
macos-P9DJ3XY0QL :: github.com/numaproj-labs/numaplane ‹cluster-name-env*› » k get deploy numaplane-controller-manager -n numaplane-system -o yaml
......
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File
- args:
- --health-probe-bind-address=:8081
- --metrics-bind-address=127.0.0.1:8080
- --leader-elect
command:
- /manager
env:
- name: CLUSTER_NAME
value: staging-usw2-k8s
image: numaplane-controller:latest
imagePullPolicy: Always
.....
```
> Add env variable for CLUSTER_NAME

- config/samples/numaplane.numaproj.io_v1alpha1_gitsync.yaml
Fixes #TODO
GitSync CRD no longer contains a "name" field in it, so needed to remove it from the sample GitSync.
successfully deployed the GitSync sample
> fix: remove name field from GitSync sample, which no longer exists

- Dockerfile
- internal/git/util.go
- internal/git/util_test.go
- internal/helm/helm.go
- internal/kustomize/kustomize.go
Fixes #110 #128
Add support to deploy helm chart repo in kubernetes cluster
**GitSync spec used for an example**
```yaml
kind: GitSync
metadata:
name: gitsync-example
namespace: numaplane-system
spec:
path: charts/numaflow
repoUrl: https://github.com/numaproj/helm-charts.git
targetRevision: main
helm: {}
destination:
cluster: staging-usw2-k8s
namespace: numaflow-pipeline
```
Tested manually in local environment
> Add support for deploy helm chart repo

- internal/git/util.go
- internal/git/util_test.go
Fixes #134
This PR use repository path as part of local repo store location. With it, GitSync.Name + GitSync.RepositoryURL will be used to uniquely identify a clone path, so that after a GitSync RepositoryURL changes, we can clone to a new location.
Unit Test
Also ensures updates to a GitSync CR are handled correctly by testing the following in a local cluster,
1.  `kubectl apply` the following GitSync spec,
```
kind: GitSync
metadata:
name: gitsync-example
namespace: numaplane-system
spec:
path: config/namespace-install
repoUrl: https://github.com/numaproj/numaflow.git
targetRevision: main
kustomize: {}
destination:
cluster: staging-usw2-k8s
names
```
2. ensure the resources are deployed successful,
3. `kubectl apply` the changed GitSync spec, …
> chore: use repository path as part of local repo store location

- Dockerfile
- config/manager/manager.yaml
- internal/helm/helm.go
- internal/shared/exec/exec.go
Fixes #100 
- Generate manifest from remote repo if referenced inside configuration of Kustomize/Helm
- Sync the changes if there is any change in remote reference, because manifest is generated each time based on latest changes from reference
Tested it on local cluster with below below GitSync CR
For kustomize
```
kind: GitSync
metadata:
name: gitsync-example
namespace: numaplane-system
spec:
path: kustmize-remote-example
repoUrl: https://github.com/chandankumar4/numaplane-sample.git
targetRevision: main
kustomize: {}
destination:
cluster: staging-usw2-k8s
namespace: numaflow-pipeline
``` 
For Helm
```
kind: GitSync
metadata:
name: gitsync-example
namespace: numaplane-system
spec:
path: helm-dependency …
```
> Fix the kustomize and helm dependency and remote changes sync

- go.mod
- go.sum
- internal/git/util.go
- internal/shared/kubernetes/kubernetes.go
- internal/shared/kubernetes/kubernetes_test.go
Fixes https://github.com/numaproj-labs/numaplane/issues/58
[IsValidKubernetesManifestFile](https://github.com/numaproj-labs/numaplane/blob/feat/filterYamlfiles/internal/shared/kubernetes/kubernetes.go#L81) function has been added which checks for the valid yaml and json files in the syncing repo from Gitsync CRD
Unit tests have been written for the above [method](https://github.com/numaproj-labs/numaplane/blob/feat/filterYamlfiles/internal/shared/kubernetes/kubernetes_test.go#L68) 
This function tests the `IsValidKubernetesManifestFile` method to ensure it correctly identifies valid Kubernetes manifest file names. It checks multiple file names with different extensions (`.md`, `.yml`, `.json`, `.yaml`, `.go`) and verifies whether the method accurately classifies each as either a valid …
> filtering yaml and json files

- internal/util/kubernetes/kubernetes.go
Fixes #NONE
Fix the error occured during build related to `Slice` package
```
$ make docker-build
------
> [builder  9/11] RUN --mount=type=cache,target="/root/.cache/go-build" CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o manager cmd/main.go:
0.449 internal/util/kubernetes/kubernetes.go:7:2: package slices is not in GOROOT (/usr/local/go/src/slices)
0.449 note: imported by a module that requires go 1.21
------
Dockerfile:29
--------------------
```
Validated via running unit test for the same
> Fix the build issue for slice package

- internal/sync/syncer.go
Clean up. This PR moves the diff comparison between target and live state into `compareState` which we do state compare.
Verified in a local cluster.
> chore: move diff comparison into `compareState` in sync

- cmd/main.go
- config/install.yaml
- config/manager/controller-config.yaml
- config/samples/config_map.yaml
- internal/controller/config/config.go
- internal/controller/config/config_test.go
- internal/sync/syncer.go
- tests/config/testconfig.yaml
- tests/config/testconfig2.yaml
- tests/manifests/config.yaml
Fixes #73
This PR adds the configuration for auto heal. By default, the auto heal is enabled with configurable intervals to verifying the cluster states match with the git state.
Unit test, also verified in a local cluster.
> Add configuration for enabling auto heal

- internal/agent/config.go
- internal/controller/config/config.go
Fixes #173 
To be honest, [this](https://github.com/numaproj-labs/numaplane/actions/runs/8393633134/job/22989032641) race condition captured in `go test -race` doesn't make sense. 
Supposedly, [this](https://github.com/numaproj-labs/numaplane/blob/main/internal/controller/config/config.go#L74) line in `v.OnConfigChange`'s function was called, and the "previous" call according to the CI which touched cm.config was [here](https://github.com/numaproj-labs/numaplane/blob/main/internal/controller/config/config.go#L62). (In my mind it is truly "previous" and not "concurrent", so I'm not sure what "go test -race" means by "previous" but I'm guessing it means "concurrent")
I don't think the function passed to `v.OnConfigChange()` should be invoked until …
> fix race condition

- cmd/agent/main.go
- cmd/main.go
- internal/agent/agent_syncer.go
- internal/agent/config.go
- internal/controller/config/config.go
- internal/sync/syncer.go
- internal/util/logger/logger.go
- internal/util/logger/logger_test.go
Added a LogLevel field to global and agent config structs to be able to load the log level from configmap. The log level is updated every time the config is retrieved again in case the level was changed in configmap.
Manually tested by inspecting the logs.
> Added log level in confi

- internal/sync/syncer.go
- internal/util/logger/logger.go
- internal/util/logger/logger_test.go
Fixes https://github.com/numaproj-labs/numaplane/issues/182
The log level mapping did not work as understood when packages call logr.Logger.Info func directly without calling the NumaLogger.Info or other function. A distinction had to be made between the 2 types of calls. For this reason, the wrapper functions (Info, Debug, etc.) call the sink Info function directly instead of setting the verbosity and then calling the Logger Info func. In addition, levels map was changed to solve additional problems with configmap not having set a log level resulting in a conflicting "zero" level. Other minor adjustments were made to avoid logging the entire gitsync manifest.
Additional unit tests were added. Additional manual comparisons between "old logs" (prior to commit …
> Logger fix

- config/rbac/role.yaml
Fixes #184 
This PR updates the Controller ClusterRole to no longer requires super user permission, instead only requires whats needed for manage Numaflow resources. 
Verified in a local cluster to deploy a Numaflow pipeline.
> Update Controller ClusterRole

- cmd/main.go
- config/install.yaml
- internal/controller/config/config.go
- internal/controller/config/config_test.go
- internal/sync/cache.go
- internal/sync/cache_test.go
- internal/sync/diff.go
- internal/sync/syncer.go
- tests/config/testconfig.yaml
- tests/manifests/config.yaml
Fixes #183 
This PR changes the cache to only watch Numaflow resources to minimize the scope of the cache. The included resources are configurable via ConfigMap.
Verified in a local cluster with the following,
```
make start
kubectl apply -k config/samples/
```
> chore: Setup the cluster cache to only watch required resources

- Makefile
- tests/e2e-gitserver/gitserver.yaml
- tests/e2e-gitserver/kustomization.yaml
- tests/e2e/manifests/config.yaml
- tests/e2e/manifests/kustomization.yaml
- tests/e2e/manifests/numaplane-ns.yaml
- tests/e2e/manifests/secret.yaml
- tests/e2e/testdata/gitsync.yaml
- tests/fixtures/given.go
Yes it fixes a bug
Fixes  https://github.com/numaproj-labs/numaplane/issues/190
**Configuration Manifests**: Introduced separate configuration manifests folder for  numaplane controller  for running e2e tests
**Makefile Enhancements**:
`e2e-test-clean`: Cleans up resources after tests to ensure a clean environment for subsequent test runs.
`e2e-test-start`: Prepares the environment for e2e testing, including setting up the NumaPlane Controller.
**GitSync YAML Update**: Modified to use Fully Qualified Domain Names (FQDN) for git urls.
**Kubernetes Secrets**: Added Kubernetes secrets to the GitSync Controller's configuration, to be used by the internal gitsync to sync repositories
These improvements were thoroughly tested in a local cluster using the `make test-e2e` command
> Fixed e2e tests configurations

- cmd/main.go
- go.mod
- internal/sync/cache.go
- internal/sync/cache_test.go
- internal/sync/syncer.go
Fixes #191 
This PR updates it to dynamically pick up config change for cache setting.
Verified in a local cluster by update the `includedResources` field in config map and see the cache setting is reloaded.
> chore: dynamically pick up config change for cache setting

- config/install.yaml
- config/manager/controller-manager.yaml
I believe common practice is to name the Deployment label the same as the Pod label? 
Chandan was modifying this in a patch within numa-manifest-generator, so seems we should just change it here instead of that.
Ran `make start` and confirmed Controller is running and has the new label.
> fix deployment label

- Makefile
- config/install.yaml
- config/manager/controller-manager.yaml
Two modifications:
1. fix repo that we are pushing to in quay.io
2. Set `initContainers` to empty array in the Deployment spec, which makes it so that I can add an array-based patch to it in `numa-manifest-generator`. (I want to add an array-based patch, so that if we ever actually add an InitContainer in the open source side, we will simply append rather than overwriting.)
> fix image repo; add initContainers to Deployment spec as empty array

- internal/git/util_test.go
No its just a bug fix .
Changed  unit tests repo from 
```
- SSH at ssh://root@localhost:2222/var/www/git/test.git
- HTTP at http://localhost:8080/git/test.git, served by the Apache HTTP server
- HTTPS at https://localhost:8443/git/test.git, secured with a self-signed certificate.
```
to 
```
- SSH at ssh://root@localhost:2222/var/www/git/repo1.git
- HTTP at http://localhost:8080/git/repo1.git, served by the Apache HTTP server 
- HTTPS at https://localhost:8443/git/repo1.git, secured with a self-signed certificate.
```
As in new local git server we are not using test.git repo but repo1.git
Running `make test`
> Fixed flaky tests

- internal/controller/gitsync_controller.go
- internal/sync/syncer.go
Clean up the log to make it concise:
- Remove gitsync dumping during deletion
- remove duplicate gitsync key logging
```
{"level":"info","worker":5,"gitSyncKey":"numaplane-system/gitsync-example","gitsync":"numaplane-system/gitsync-example","logger":"numaplane.synchronizer","caller":"sync/sync_context.go:387","ts":"2024-04-22T22:52:38.786274777Z","msg":"Syncing"}
{"level":"info","worker":5,"gitSyncKey":"numaplane-system/gitsync-example","gitsync":"numaplane-system/gitsync-example","logger":"numaplane.synchronizer","caller":"sync/sync_context.go:409","ts":"2024-04-22T22:52:38.792280194Z","msg":"Tasks (dry-run)"}
{"level":"info","worker":5,"gitSyncKey":"numaplane-system/gitsync-example","gitsync":"numaplane-system/gitsync-example","logger":"numaplane.synchronizer","caller":"sync/sync_context …
```
> chore: Log clean up

- tests/e2e/functional_test.go
- tests/e2e/manifests/kustomization.yaml
- tests/e2e/testdata/helm-gitsync-params.yaml
- tests/e2e/testdata/helm-gitsync.yaml
- tests/e2e/testdata/helm/initial-commit/.helmignore
- tests/e2e/testdata/helm/initial-commit/Chart.yaml
- tests/e2e/testdata/helm/initial-commit/templates/NOTES.txt
- tests/e2e/testdata/helm/initial-commit/templates/_helpers.tpl
- tests/e2e/testdata/helm/initial-commit/templates/deployment.yaml
- tests/e2e/testdata/helm/initial-commit/templates/hpa.yaml
- tests/e2e/testdata/helm/initial-commit/templates/ingress.yaml
- tests/e2e/testdata/helm/initial-commit/templates/serviceaccount.yaml
- tests/e2e/testdata/helm/initial-commit/values.yaml
- tests/e2e/testdata/helm/modified/templates/new-deploy.yaml
- tests/e2e/testdata/helm/modified/values.yaml
- tests/e2e/testdata/kustomize/initial-commit/configmap.yaml
- tests/e2e/testdata/kustomize/initial-commit/deployment.yaml
- tests/e2e/testdata/kustomize/initial-commit/secret.yaml
Fixes #228 
Adds e2e test case using Helm manifests. The Helm resources used were generated using `helm create`.
Added Helm manifest to testdata directory.
Tested that Helm templated resources are created and deleted when being added to or removed from repository.
Ran `make test-e2e` multiple times.
> test: add e2e test case for Helm manifests

- internal/sync/syncer.go
Fixes #235 
This PR supports to turn off auto heal if it is configured so.
Tested in a local cluster with `autoHealTimeIntervalMs` not set.  Auto heal is off so the syncing is skipped if no new changes.
> chore: support for turning off auto heal

- .github/workflows/ci.yaml
- internal/git/util.go
- internal/git/util_test.go
- internal/util/git/git.go
Fixes https://github.com/numaproj-labs/numaplane/issues/226
Modifications
In this PR I have added a provision to checkout to the particular target revision as present in gitsync spec
1- If the target revision is branch then it directly checks out to the branch as mentioned [here](https://github.com/numaproj-labs/numaplane/blob/f051b9c9b47b0156203a19ff9e4b4c5b14bffc15/internal/git/util.go#L356) 
2- If target revision is tag then  it finds the first   branch which has that tag [here](https://github.com/numaproj-labs/numaplane/blob/f051b9c9b47b0156203a19ff9e4b4c5b14bffc15/internal/git/util.go#L299)  and then  checks out to that branch
3- If target revision is commit hash  then it finds the first branch which has that commit hash [here](https://github.com/numaproj-labs/numaplane/blob/f051b9c9b …
> Added reference name in clone options for git clone

- internal/git/util.go
- internal/git/util_test.go
- internal/util/git/git.go
Fixes #244
This PR updates git Fetch options take auth as well.
Tried with gisync in local cluster
```
kind: GitSync
metadata:
name: oss-analytics-shakira-test-control-repo1-qal-usw2-eks
namespace: oss-analytics-shakiratestcontrolrepo1-usw2-qal
spec:
path: ""
repoUrl: https://github.intuit.com/oss-analytics/shakira-test-control-repo1-deployment.git
targetRevision: environments/qal-usw2-eks
raw: {}
destination:
cluster: ip-msaas-ppd-usw2-k8s
namespace: oss-analytics-shakiratestcontrolrepo1-usw2-qal
```
> fix: git fetch should include credentials

- cmd/main.go
- go.mod
- internal/git/util.go
- internal/git/util_test.go
- internal/metrics/metrics.go
- internal/metrics/transportwrapper.go
- internal/sync/syncer.go
- internal/sync/syncer_test.go
Fixes #138 
Added below metrics:
**Syncing**
**K8s API calls** (during syncing/cache)
**Cache**
**Git access**
Saturation
> feat: Add numaplane metrics support

- internal/git/util.go
- internal/git/util_test.go
Fixes #258 
This PR fetch remote refs during each sync reconcilation if necessary so switching branches in existing gitsync works.
e2e test [here](https://github.com/numaproj-labs/numaplane/commit/f9008a8cfa526405cbacfd1e8a0b88f4a1a7d823) works
> Fetch remote refs during each sync reconcilation

- go.mod
- internal/git/util.go
- internal/util/git/git.go
- internal/util/git/git_test.go
- internal/util/git/testdata/gitconfig/gitconfig-nourlauth
- internal/util/git/testdata/gitconfig/gitconfig-urlonly
- internal/util/git/testdata/gitconfig/gitconfig-valid
- internal/util/logger/logger.go
Fixes https://github.com/numaproj-labs/numaplane/issues/262
Added a function to load the gitconfig file and apply URL mapping and Authorization config options if available for cloning and fetching operations.
Tested manually by running the controller on K8s cluster with and without the URL mappings and Authorization extraheader in gitconfig file.
> Sync with git config file

- .github/workflows/ci.yaml
- Makefile
- tests/e2e/functional_test.go
- tests/e2e/testdata/branch-gitsync.yaml
- tests/fixtures/given.go
Fixes #248 
Adds test case called `TestNonMainBranch` to test that GitSync works properly when `targetRevision` is set to a branch other than main or master. This done by creating a new branch `test` and pushing to it to see that changes on the resources are reflected by it. We also test changing back to the master branch.
Ran `make test-e2e`
> test: e2e test case for using branches other than main/master

- cmd/agent/main.go
- cmd/main.go
- internal/controller/gitsync_controller.go
- internal/git/util.go
- internal/sync/cache.go
- internal/sync/options.go
- internal/sync/syncer.go
- internal/util/git/git.go
- internal/util/logger/base_logger.go
- internal/util/logger/logger.go
- internal/util/logger/logger_test.go
We are using the [context to get the Logger](https://github.com/numaproj-labs/numaplane/blob/v0.1.2/internal/sync/syncer.go#L117), but we don't ever update the context to reflect that the Logger changed.
I added a Base Logger for the application, which is essentially the original Logger but with the Log level periodically updated based on the Config. 
Long living goroutines periodically refresh the Base Logger with the current log level and get a copy of it, add any Values they want logged, and then update the context to include that Logger, so downstream users will log those same values automatically. 
Updated logLevel from `info` to `debug` level back and forth, and witnessed the log lines change. Verified for both calls in `syncer.runOnce()`, calls from functions called downstream of …
> update context when loglevel is updated

- internal/common/common.go
- internal/sync/cache.go
- internal/sync/cache_test.go
- internal/sync/syncer.go
- internal/sync/testdata/pipeline-live.yaml
- internal/util/kubernetes/kubernetes.go
- internal/util/kubernetes/kubernetes_test.go
Fixes #214 
GitSync resources currently get an annotation added: `numaplane.numaproj.io/tracking-id: gitsync-example`
This PR converts this annotation to a label instead. This will allow for the use of a label selector in the future to select resources by GitSync.
Created example GitSyncs and checked that created resources had correct label and didn't have previous annotation.
> feat: replacing GitSync annotation with label

- config/install.yaml
- config/manager/controller-config.yaml
- internal/controller/config/config_test.go
- tests/config/testconfig.yaml
- tests/e2e/manifests/config.yaml
- tests/e2e/manifests/from-json-config.yaml
- tests/e2e/manifests/from-yaml-config.yaml
- tests/manifests/config.yaml
Fixes cache filter config to correctly include `numaplane.numaproj.io`.
e2e Test
> fix: typo in cache filter config

- cmd/main.go
Fix panics caused when updating controller-runtime [here](https://github.com/numaproj-labs/numaplane/pull/308/files).
Panics like this:
```
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
>  goroutine 143 [running]:
>  runtime/debug.Stack()
>      /usr/local/go/src/runtime/debug/stack.go:24 +0x64
>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
>      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/log/log.go:60 +0xf4
>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Error(0x4000186500, {0x25ff980, 0x40006af480}, {0x211654c, 0x3d}, {0x40003be880, 0x2, 0x2})
>      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/log/deleg.go:139 +0x44
>  github.com/go-logr/logr.Logger.Error({{0x2626f08?, …
```
> fix: panics in controller-runtime

- config/samples/numaplane.numaproj.io_v1alpha1_isbservicerollout.yaml
- config/samples/numaplane.numaproj.io_v1alpha1_numaflowcontrollerrollout.yaml
- config/samples/numaplane.numaproj.io_v1alpha1_pipelinerollout.yaml
- internal/controller/isbservicerollout_controller.go
- internal/controller/pipelinerollout_controller.go
- internal/kubernetes/dynamic_client.go
- pkg/apis/numaplane/v1alpha1/groupversion_info.go
This includes all of the reconciliation logic, with exception to the Status functions that Tony is working on (there are "todo" placeholders for those).
Tested by doing the following for both PipelineRollout and ISBServiceRollout:
- created Rollout object from our `samples` directory
- verified finalizer added to it
- verified ownerreference added to child object
- updated Rollout object spec (observed that child object changed, or in the case of ISBService, the numflow webhook denied the change as not allowed)
- deleted Rollout object and observed that child object got deleted
> Pipeline Controller and ISBService Controller reconciliation logic

- config/crd/bases/numaplane.numaproj.io_gitsyncs.yaml
- config/crd/bases/numaplane.numaproj.io_isbservicerollouts.yaml
- config/crd/bases/numaplane.numaproj.io_numaflowcontrollerrollouts.yaml
- config/crd/bases/numaplane.numaproj.io_pipelinerollouts.yaml
- config/install.yaml
- pkg/apis/numaplane/v1alpha1/gitsync_types.go
- pkg/apis/numaplane/v1alpha1/isbservicerollout_types.go
- pkg/apis/numaplane/v1alpha1/numaflowcontrollerrollout_types.go
- pkg/apis/numaplane/v1alpha1/pipelinerollout_types.go
- pkg/apis/numaplane/v1alpha1/status_types.go
Added columns Phase and Age to the output of the `kubectl get <crd-name>` command.
`kubectl -n example-namespace get pipelinerollout`
> Print column phase

- cmd/main.go
- config/install.yaml
- config/manager/controller-manager.yaml
- internal/common/common.go
- internal/controller/config/config.go
- internal/controller/config/config_test.go
- internal/controller/config/options.go
- internal/controller/numaflowcontrollerrollout_controller.go
- internal/sync/cache.go
- internal/sync/cache_test.go
- internal/sync/syncer.go
- internal/util/kubernetes/kubernetes.go
- internal/util/kubernetes/kubernetes_test.go
- tests/config/controller-definitions-config.yaml
- tests/manifests/controller_definitions.yaml
This PR adds the reconciliation logic for NumaflowControllerRollout.
Tested in local cluster,
- `make start`
- `kubectl apply -f config/samples/numaplane.numaproj.io_v1alpha1_numaflowcontrollerrollout.yaml`
Verified Numaflow Controller successfully deployed to `example-namespace`.
> Apply NumaflowController Spec

- tests/manifests/kustomization.yaml
only `numaflow-controller-definitions-config` should be immutable
`kubectl edit configmaps numaplane-controller-config -n numaplane-system` show `immutable: true` no longer there.
> fix: only `numaflow-controller-definitions-config` should be immutable
