.github/workflows/ci.yaml
Closes #20 
Adds CI with unit-test and lint as a starter.
=> chore: add github ci

Makefile, README.md, config/manager/kustomization.yaml, config/manager/manager.yaml
image name was by default "controller:latest". Changing to include VERSION and better name. 
I presume we will make more changes to the Makefile in the future, but thought I'd start with this.
=> change default image name to something more meaningful

go.mod, go.sum, internal/git/gitsync_processor.go, internal/git/gitsync_processor_test.go
Closes #25 and #45 
This PR stores the recent commit if the resources successfully applied. If not, the whole process will be retried.
It also ensures with a previous persisted commit status, we just monitor and apply the changes in-between.
=> feat: Stores the recent commit in the GitSync Status

internal/git/gitsync_processor.go
We returned early after the very first resources apply of the GitSyncProcessor. This PR also updates the fetch option so we have a mapping from local branches to remote references to be able to resolve the latest commit hash.
=> chore: avoid return early after first resources apply of the GitSyncProcessor

internal/git/gitsync_processor.go, internal/git/gitsync_processor_test.go
https://github.com/numaproj-labs/numaplane/issues/69
=> Object Not found Issue 69

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
=> Add issue template

.gitignore
Ignore `.DS_Store` file in all directory in .gitignore
=> chore: Ignore `.DS_Store` file in all directory

Makefile, config/manager/config.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, tests/manifests/kustomization.yaml
`make deploy` to run the controller in a local cluster without pushing images.
=> chore: Ability to run in local cluster without pushing images

Makefile
- Clean up some useless scripts such as `make install`, `make uninstall`, `make undeploy`.
- Update `make deploy` to `make start` to make it consistent with Numaflow.
- Remove `kustomize` dependency, use `kubectl kustomize` instead.
=> chore: clean up some useless scripts

Makefile, config/install.yaml, config/manager/config.yaml, tests/manifests/config.yaml, tests/manifests/kustomization.yaml
Fixes #121 
Add "make manifests" command to generate `install.yaml`
Verified by applying install.yaml in local k8s cluster
=> Add Make manifests command to generate install.yaml

internal/git/util.go, internal/git/util_test.go
- Fix the authentication issue for updating the cloned repo.
- Verified it on local kind cluster as well as iksm cluster
=> bug: Fix the auth for repo update

Dockerfile, cmd/main.go
=> chore: logging fix

internal/git/util.go, internal/git/util_test.go, internal/sync/syncer.go
Fixes #133 
This PR adds commit status after each sync even when there is a sync failure.
Verified in a local cluster.
=> Add commit status after syncing

internal/sync/syncer.go
Fixes #198 
- FIx the resource deletion if it's get deleted from repo
- Verified in local kubernetes cluster with deleting the resource from repo after creating it.
=> bug: Fix the resource deletion if removed from repo

internal/sync/syncer.go
Fixes #200 
- Enable serverSideDiff Option when comparing diff as we are using serverSideApply.
Tested in local k8s cluster, these are dry-run logs
```bash
{"level":"info","logger":"numaplane","caller":"kube/resource_ops.go:251","ts":"2024-04-17T14:51:42.548199+05:30","msg":"Applying resource ConfigMap/numaflow-controller-config in cluster: https://127.0.0.1:49383, namespace: numaflow-pipeline"}
{"level":"info","logger":"numaplane","caller":"kube/resource_ops.go:251","ts":"2024-04-17T14:51:42.555639+05:30","msg":"Applying resource Deployment/numaflow-controller in cluster: https://127.0.0.1:49383, namespace: numaflow-pipeline"}
{"level":"info","logger":"numaplane","caller":"kube/resource_ops.go:251","ts":"2024-04-17T14:51:42.5637+05:30","msg":"Applying resource …
```
=> Enable server side diff for comparing resources

internal/git/util.go, internal/git/util_test.go, internal/util/git/git.go, internal/util/git/git_test.go
Fixes #218 
- After sync the repo status looks fine also it's able to delete/create any resource accordingly 
Verified in local k8s cluster using below gitsync
```bash
kind: GitSync
metadata:
name: gitsync-example
namespace: numaplane-system
spec:
path: "kustomize-example/cluster-install"
repoUrl: https://github.com/chandankumar4/numaplane-sample.git
targetRevision: main
kustomize: {}
destination:
cluster: staging-usw2-k8s
namespace: numaflow-pipeline
```
=> Fix the cloned repo update issue

cmd/main.go, config/install.yaml, config/manager/controller-config.yaml, config/samples/config_map.yaml, internal/controller/config/config.go, internal/controller/config/config_test.go, internal/sync/syncer.go, tests/config/testconfig.yaml, tests/config/testconfig2.yaml, tests/e2e/manifests/config.yaml, tests/manifests/config.yaml
Fixes #239 
Separate auto heal and syncing interval configs
Verified in the local cluster.
=> chore: refactor auto heal config

internal/git/util_test.go
No
Renamed the target revision as main ,from controlledTestsEn as now the required files are available in the main branch
Running unit tests using `make test`
=> Modified target revision for test to main

config/install.yaml, config/manager/controller-config.yaml, config/rbac/role.yaml
Fixes #243 
This PR updates ClusterRole with minimal permissions if without namespace rolebing.
Tested in local cluster
=> Update ClusterRole with minimal permissions

config/install.yaml, config/manager/controller-config.yaml, config/samples/config_map.yaml, internal/controller/config/config.go, internal/controller/config/config_test.go, internal/sync/syncer.go, tests/config/testconfig.yaml, tests/config/testconfig2.yaml, tests/e2e/manifests/config.yaml, tests/fixtures/when.go, tests/manifests/config.yaml
Fixes #255 
Support disabling automated sync for all gitsyncs in the cluster.
=> chore: support for disable automated sync

tests/gitserver/Dockerfile
Yes
Fixes  https://github.com/numaproj-labs/numaplane/issues/270
I had to modify the Apache server configuration for LocalGitServer because there was an issue resolving public Git URLs. The location matching for `/gitopen` was getting redirected to '/git', which requires authentication, so I changed `/gitopen` to `/public-git`. 
Tests running on local cluster and unit tests
=> Modified Dockerfile For LocalGitServer public git URL

internal/git/util_test.go
No
Modified Some tests  in `util_test.go`  to fix flaky unit tests.
By running unit tests `make test`
=> Fixed Flaky Unit tests

config/default/manager_config_patch.yaml, config/install.yaml
Fixes: No ISSUE
FIx the metrics endpoint access issue outside pod/container
=> Fix the metrix access issue outside container

.github/workflows/release.yml
=> fix: Remove build dependency

Makefile, config/crd/bases/numaplane.numaproj.io_gitsyncs.yaml, config/install.yaml
Seems some people are seeing a panic when using controller-gen v0.13.0
=> update controller-gen to v0.14.0

config/install.yaml, config/manager/numaflow-controller-definitions-config.yaml
Update the `install.yaml`
`kubectl apply -f config/install.yaml -n numaplane-system`
=> fix: update install.yaml

internal/controller/numaflowcontrollerrollout_controller.go, internal/sync/syncer.go, internal/util/kubernetes/kubernetes.go, internal/util/kubernetes/kubernetes_test.go
Add owner reference when deploying Numaflow controller
Verified if NumaflowControllerRollout CR is deleted, the underlying numaflow controller is deleted.
=> Add OwnerReference to Numaflow controller

.github/workflows/ci.yaml, .github/workflows/release.yml
Fixes #150 
ran `make image CONTAINER_TOOL=docker IMAGE_FULL_PATH=quay.io/numaproj/numaplane-controller:latest` on terminal to build image. picture below
=> Dev Add Image build steps in CI process
